In [0]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor

In [217]:
data=datasets.fetch_covtype()

In [218]:
data.keys()

dict_keys(['data', 'target', 'DESCR'])

In [0]:
x=data.data
y=data.target

In [0]:
X_train,X_test,y_train,y_test=train_test_split(x,y, test_size=0.3 , random_state=42)

In [222]:
model=RandomForestClassifier(n_estimators=300, random_state=42)

model.fit(X_train,y_train)
predict=model.predict(X_test)

print("Accuracy:", metrics.accuracy_score(y_test,predict))
print("matrix:", metrics.confusion_matrix(y_test,predict))


Accuracy: 0.9523877822654673
matrix: [[59710  3681     3     0    20     7   135]
 [ 1939 82725   167     0   120    93    34]
 [    4   164 10214    37    10   209     0]
 [    0     0   100   676     0    19     0]
 [   54   604    41     0  2224    18     0]
 [    5   161   346    23     3  4689     0]
 [  268    34     0     0     0     0  5767]]


In [226]:
from sklearn.model_selection import RandomizedSearchCV# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 3, 6, 5, 8, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4, 5, 6, 8, 9]


# Method of selecting samples for training each tree
bootstrap = [True, False]# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap
              }

random_grid

{'bootstrap': [True, False],
 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, None],
 'max_features': ['auto', 'sqrt'],
 'min_samples_leaf': [1, 2, 4, 5, 6, 8, 9],
 'min_samples_split': [2, 3, 6, 5, 8, 10],
 'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]}

In [0]:
rf = RandomForestClassifier()
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations, and use all available cores
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 10, cv = 2, verbose=2, random_state=42, n_jobs = -1)# Fit the random search model
rf_random.fit(X_train, y_train)

Fitting 2 folds for each of 10 candidates, totalling 20 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
